services:

  #PRODUCTION (standalone mode)
  frontend-prod:
    profiles: ["frontend-prod"]
    image: adolfiscariot/social_listening:frontend-1.0.0
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
    restart:
      unless-stopped
    depends_on:
      - linkedinsociallistening
    networks:
      - app-network
    env_file:
      - ./next/.env

  # BACKEND
  linkedinsociallistening:
    profiles: ["backend"]
    image: adolfiscariot/social_listening:backend-1.0.0
    ports:
      - "5002:5002"
    env_file:
      - ./backend/.env
    depends_on:
      - db
    networks:
      - app-network
    restart:
      unless-stopped

  # DATABASE
  db:
    image: postgres:17
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: social_listening
      POSTGRES_USER: mark_mathenge
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - db_password 
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mark_mathenge -d social_listening"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 30s

secrets:
  db_password: 
    file: db_password.txt

volumes:
  pgdata:

networks:
  app-network:
    driver: bridge
