import psycopg

#create connection to database
with psycopg.connect(conninfo="host=localhost dbname=sl port=5432 user=postgres password=markothengo99") as conn:
    #create cursor to navigate database
    with conn.cursor() as cur:
        #execute commands
        try:
            cur.execute("""
                CREATE TABLE IF NOT EXISTS leads(
                    lead_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                    author_id INTEGER NOT NULL UNIQUE,
                    company_id INTEGER,
                    date DATE NOT NULL, 
                    CONSTRAINT fk_author FOREIGN KEY(author_id) REFERENCES authors(author_id),
                    CONSTRAINT fk_company FOREIGN KEY(company_id) REFERENCES companies(company_id))
            """)
            conn.commit()
            print("Database update successful")
        except Exception as e:
            print("Error: ", e)